name: Example Workflow

on: 
  push:
    branches: ['main']
    
  workflow_dispatch:

env:
  HOST: 161.35.118.112
  USER: root

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_DIGITAL_OCEAN_RSA }}
          name: id_digital_ocean_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Say Hello
        run: |
          echo Hello!

      - name: Look Around
        run: |
          echo '$ pwd'
          pwd
          echo '$ ls -la'
          ls -la

      - name: Look Around On The Server
        run: |
          ssh -i ~/.ssh/id_digital_ocean_rsa $USER@$HOST ls -la

      - name: Transfer a file
        run: |
          echo "hello!" >hello.txt
          echo "---"
          ssh -i ~/.ssh/id_digital_ocean_rsa $USER@$HOST ls -la
          echo "---"
          scp -i ~/.ssh/id_digital_ocean_rsa hello.txt $USER@$HOST:.
          echo "---"
          ssh -i ~/.ssh/id_digital_ocean_rsa $USER@$HOST ls -la
          echo "---"

      - name: Transfer it back
        run: |
          echo rm hello.txt
          echo "---"
          ls -la
          echo "---"
          scp -i ~/.ssh/id_digital_ocean_rsa $USER@$HOST:./hello.txt .
          echo "---"
          ls -la
          echo "---"

      - name: Clean up that remote file
        run: |
          echo "hello!" >hello.txt
          echo "---"
          ssh -i ~/.ssh/id_digital_ocean_rsa $USER@$HOST ls -la
          echo "---"
          ssh -i ~/.ssh/id_digital_ocean_rsa $USER@$HOST rm ./hello.txt
          echo "---"
          ssh -i ~/.ssh/id_digital_ocean_rsa $USER@$HOST ls -la
          echo "---"

      - name: Say Goodbye
        run: |
          echo Goodbye!

